"""
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

# o(n) time o(1) space
def naive():
  term1 = 1
  term2 = 2
  total = 2
  while term2 <= 4000000:
    temp = term1 + term2
    total += temp if temp % 2 == 0 else 0
    term1 = term2
    term2 = temp

  return total


# only need every third term up to the first term > 4,000,000
if __name__ == '__main__':
  print(naive())
